# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0003_zonariesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('codactividad', models.AutoField(db_column='CodActividad', primary_key=True, serialize=False)),
                ('ordenactividad', models.IntegerField(blank=True, db_column='OrdenActividad', null=True)),
                ('nombreactividad', models.CharField(blank=True, db_column='NombreActividad', max_length=200, null=True)),
                ('descripcionactividad', models.TextField(blank=True, db_column='DescripcionActividad', null=True)),
                ('tiempo', models.IntegerField(blank=True, db_column='Tiempo', null=True)),
                ('fecha_control', models.DateTimeField(blank=True, db_column='FechaControl', null=True)),
                ('habilitado', models.NullBooleanField()),
                ('anexo', models.FileField(blank=True, db_column='Anexo', max_length=150, null=True, upload_to='upload/')),
                ('anexoimg', models.BinaryField(blank=True, db_column='AnexoImg', null=True)),
            ],
            options={
                'db_table': 'Actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('codcontrol', models.AutoField(db_column='CodControl', primary_key=True, serialize=False)),
                ('efectividad', models.DecimalField(blank=True, db_column='Efectividad', decimal_places=1, max_digits=5, null=True)),
                ('nivel_riesgo_residual', models.IntegerField(blank=True, db_column='NivelRiesgoResidual', null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=150, null=True)),
                ('zona_riesgo', models.CharField(blank=True, db_column='ZonaRiesgo', max_length=100, null=True)),
                ('valoracion_control', models.DecimalField(blank=True, db_column='ValoracionControl', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Controles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DuenosSubproceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DuenosXSubProceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raci',
            fields=[
                ('idraci', models.AutoField(db_column='IdRaci', primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=150, null=True)),
            ],
            options={
                'db_table': 'RACI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subprocesos',
            fields=[
                ('codsubproceso', models.AutoField(db_column='CodSubproceso', primary_key=True, serialize=False)),
                ('descsubproceso', models.TextField(blank=True, db_column='DescSubProceso', null=True)),
                ('orden_subproceso', models.IntegerField(blank=True, db_column='OrdenSubproceso', null=True)),
                ('diagrama', models.FileField(blank=True, db_column='Diagrama', max_length=150, null=True, upload_to='upload/')),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('anexo', models.CharField(blank=True, db_column='Anexo', max_length=75, null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
                ('narrativa', models.TextField(blank=True, db_column='Narrativa', null=True)),
            ],
            options={
                'db_table': 'SubProcesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subprocesosxescenarios',
            fields=[
                ('codsubprocesosxescenarios', models.AutoField(db_column='CodSubProcesosXEscenarios', primary_key=True, serialize=False)),
                ('escenario', models.CharField(blank=True, db_column='EscenarioRiesgo', max_length=200, null=True)),
                ('probabilidad', models.IntegerField(blank=True, db_column='Probabilidad', null=True)),
                ('impacto', models.IntegerField(blank=True, db_column='Impacto', null=True)),
                ('nivel_riesgo_inherente', models.IntegerField(blank=True, db_column='NivelRiesgoInherente', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=150, null=True)),
                ('linea_negocio_nivel1', models.CharField(blank=True, db_column='LineaNegocioNivel1', max_length=150, null=True)),
                ('linea_negocio_nivel2', models.CharField(blank=True, db_column='LineaNegocioNivel2', max_length=150, null=True)),
                ('zonariesgo', models.CharField(blank=True, db_column='ZonaRiesgo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SubProcesosXEscenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRiesgoSubprocesosEscenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TipoRiesgoXSubProcesosXEscenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.CharField(blank=True, db_column='Introduccion', max_length=1000, null=True)),
                ('objetivos', models.CharField(blank=True, db_column='Observaciones', max_length=1000, null=True)),
                ('alcance', models.CharField(blank=True, db_column='Alcance', max_length=1000, null=True)),
                ('responsabilidad', models.CharField(blank=True, db_column='Responsabilidad', max_length=1000, null=True)),
                ('revision', models.CharField(blank=True, db_column='Revision', max_length=1000, null=True)),
                ('cumplimiento', models.CharField(blank=True, db_column='Cumplimiento', max_length=1000, null=True)),
                ('excepciones', models.CharField(blank=True, db_column='Excepciones', max_length=1000, null=True)),
                ('definiciones', models.CharField(blank=True, db_column='Definiciones', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'InformacionGeneral',
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('codproceso', models.AutoField(db_column='CodProceso', primary_key=True, serialize=False)),
                ('nombre_proceso', models.CharField(blank=True, db_column='NombreProceso', max_length=75, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('logo', models.BinaryField(blank=True, db_column='Logo', null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
                ('logoimagen', models.FileField(blank=True, db_column='LogoImagen', max_length=150, null=True, upload_to='upload/')),
                ('codtipoproceso', models.ForeignKey(blank=True, db_column='CodTipoProceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Tipoproceso')),
                ('estado', models.ForeignKey(blank=True, db_column='Estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Estados')),
                ('idduenoproceso', models.ForeignKey(blank=True, db_column='IdDuenoProceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Puestos')),
            ],
            options={
                'db_table': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='DescripcionUnidadMedida', max_length=100, null=True)),
            ],
            options={
                'db_table': 'UnidadesMedida',
            },
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='proceso',
            field=models.ForeignKey(blank=True, db_column='CodProceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procesos.Procesos'),
        ),
    ]
