# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_escnariosriesgos_riesgos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('codactividad', models.AutoField(db_column='CodActividad', primary_key=True, serialize=False)),
                ('ordenactividad', models.IntegerField(blank=True, db_column='OrdenActividad', null=True)),
                ('descripcionactividad', models.TextField(blank=True, db_column='DescripcionActividad', null=True)),
            ],
            options={
                'db_table': 'Actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raci',
            fields=[
                ('idraci', models.AutoField(db_column='IdRaci', primary_key=True, serialize=False)),
                ('codpuesto', models.IntegerField(blank=True, db_column='CodPuesto', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=150, null=True)),
            ],
            options={
                'db_table': 'RACI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subprocesos',
            fields=[
                ('codsubproceso', models.AutoField(db_column='CodSubproceso', primary_key=True, serialize=False)),
                ('descsubproceso', models.TextField(blank=True, db_column='DescSubProceso', null=True)),
                ('orden_subproceso', models.IntegerField(blank=True, db_column='OrdenSubproceso', null=True)),
                ('diagrama', models.BinaryField(blank=True, db_column='Diagrama', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('anexo', models.CharField(blank=True, db_column='Anexo', max_length=75, null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
            ],
            options={
                'db_table': 'SubProcesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subprocesosxescenarios',
            fields=[
                ('codsubprocesosxescenarios', models.AutoField(db_column='CodSubProcesosXEscenarios', primary_key=True, serialize=False)),
                ('probabilidad', models.IntegerField(blank=True, db_column='Probabilidad', null=True)),
                ('impacto', models.IntegerField(blank=True, db_column='Impacto', null=True)),
                ('nivel_riesgo_inherente', models.IntegerField(blank=True, db_column='NivelRiesgoInherente', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=150, null=True)),
            ],
            options={
                'db_table': 'SubProcesosXEscenarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('codproceso', models.AutoField(db_column='CodProceso', primary_key=True, serialize=False)),
                ('nombre_proceso', models.CharField(blank=True, db_column='NombreProceso', max_length=75, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('logo', models.BinaryField(blank=True, db_column='Logo', null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
                ('codtipoproceso', models.ForeignKey(blank=True, db_column='CodTipoProceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Tipoproceso')),
                ('estado', models.ForeignKey(blank=True, db_column='Estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Estados')),
                ('idduenoproceso', models.ForeignKey(blank=True, db_column='IdDuenoProceso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Puestos')),
            ],
            options={
                'db_table': 'Procesos',
            },
        ),
    ]
