# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaNormativa',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codproceso', models.IntegerField(blank=True, db_column='CodProceso', null=True)),
                ('circular', models.CharField(blank=True, db_column='Circular', max_length=300, null=True)),
            ],
            options={
                'db_table': 'CedulaNormativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadoresDesempenio',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codproceso', models.IntegerField(blank=True, db_column='CodProceso', null=True)),
                ('definicion', models.CharField(blank=True, db_column='Definicion', max_length=500, null=True)),
                ('aceptable', models.CharField(blank=True, db_column='Aceptable', max_length=500, null=True)),
                ('inaceptable', models.CharField(blank=True, db_column='Inaceptable', max_length=500, null=True)),
                ('periodo_medicion', models.CharField(blank=True, db_column='PeriodoMedicion', max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'IndicadoresDesempenio',
                'managed': False,
            },
        ),
    ]
