# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('codcontrol', models.AutoField(db_column='CodControl', primary_key=True, serialize=False)),
                ('efectividad', models.IntegerField(blank=True, db_column='Efectividad', null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, db_column='NivelRiesgo', null=True)),
                ('riesgo_residual', models.IntegerField(blank=True, db_column='RiesgoResidual', null=True)),
                ('fecha_implementacion', models.DateTimeField(blank=True, db_column='FechaImplementacion', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Controles',
                'managed': False,
            },
        ),
    ]
