# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_cedulanormativa_indicadoresdesempenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesSubprocesos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('diagrama', models.FileField(blank=True, db_column='Diagrama', max_length=150, null=True, upload_to='upload/')),
                ('imagen_diagrama', models.BinaryField(blank=True, db_column='ImagenDiagrama', null=True)),
            ],
            options={
                'db_table': 'ImagenesXSubprocesos',
                'managed': False,
            },
        ),
    ]
