# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('codarea', models.AutoField(db_column='CodArea', primary_key=True, serialize=False)),
                ('descarea', models.CharField(blank=True, db_column='DescArea', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codestado', models.AutoField(db_column='CodEstado', primary_key=True, serialize=False)),
                ('descestado', models.CharField(blank=True, db_column='DescEstado', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naturalezacontrol',
            fields=[
                ('codnaturaleza', models.AutoField(db_column='CodNaturaleza', primary_key=True, serialize=False)),
                ('descnaturaleza', models.CharField(blank=True, db_column='DescNaturaleza', max_length=150, null=True)),
            ],
            options={
                'db_table': 'NaturalezaControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('codpuesto', models.AutoField(db_column='CodPuesto', primary_key=True, serialize=False)),
                ('descpuesto', models.CharField(blank=True, db_column='DescPuesto', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Puestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoactividad',
            fields=[
                ('codtipoactividad', models.AutoField(db_column='CodTipoActividad', primary_key=True, serialize=False)),
                ('desctipoactividad', models.CharField(blank=True, db_column='DescTipoActividad', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoActividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoareas',
            fields=[
                ('codtipoarea', models.AutoField(db_column='CodTipoArea', primary_key=True, serialize=False)),
                ('desctipoarea', models.CharField(blank=True, db_column='DescTipoArea', max_length=75, null=True)),
            ],
            options={
                'db_table': 'TipoAreas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrol',
            fields=[
                ('codtipocontrol', models.AutoField(db_column='CodTipoControl', primary_key=True, serialize=False)),
                ('desctipocontrol', models.CharField(blank=True, db_column='DescTipoControl', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproceso',
            fields=[
                ('codtipoproceso', models.AutoField(db_column='CodTipoProceso', primary_key=True, serialize=False)),
                ('desctipoproceso', models.CharField(blank=True, db_column='DescTipoProceso', max_length=75, null=True)),
            ],
            options={
                'db_table': 'TipoProceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporaci',
            fields=[
                ('codraci', models.AutoField(db_column='CodRaci', primary_key=True, serialize=False)),
                ('letra', models.CharField(blank=True, db_column='Letra', max_length=1, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoRACI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposriesgos',
            fields=[
                ('codtiporiesgo', models.AutoField(db_column='CodTipoRiesgo', primary_key=True, serialize=False)),
                ('desctiporiesgo', models.CharField(blank=True, db_column='DescTipoRiesgo', max_length=75, null=True)),
            ],
            options={
                'db_table': 'TiposRiesgos',
                'managed': False,
            },
        ),
    ]
