# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('codarea', models.AutoField(db_column='CodArea', primary_key=True, serialize=False)),
                ('descarea', models.CharField(blank=True, db_column='DescArea', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreasInvolucradas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionAreasInvolucradas', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'AreasInvolucradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaRiesgos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codcategoria', models.CharField(blank=True, db_column='CodCategoria', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DescripcionCategoria', max_length=300, null=True)),
            ],
            options={
                'db_table': 'CategoriaRiesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CumplimientoNormativo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionCumplimientoNormativo', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'CumplimientoNormativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefinicionProceso',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionDefinicionProceso', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'DefinicionProceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado', models.AutoField(db_column='CodEmpleado', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=75, null=True)),
                ('usuarioad', models.CharField(blank=True, db_column='UsuarioAD', max_length=75, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=75, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=75, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=75, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoxAreas',
            fields=[
                ('empleadoarea', models.AutoField(db_column='CodEmpeladoXArea', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='FechaInicio', null=True)),
                ('fecha_final', models.DateTimeField(blank=True, db_column='FechaFinal', null=True)),
                ('habilitado', models.NullBooleanField(db_column='Habilitado')),
            ],
            options={
                'db_table': 'EmpleadoXAreas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escalaimpacto',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('escala', models.IntegerField(blank=True, db_column='Escala', null=True)),
                ('desde', models.DecimalField(blank=True, db_column='Desde', decimal_places=1, max_digits=5, null=True)),
                ('hasta', models.DecimalField(blank=True, db_column='Hasta', decimal_places=1, max_digits=5, null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'EscalaImpacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escalaprobabilidad',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('escala', models.IntegerField(blank=True, db_column='Escala', null=True)),
                ('desde', models.DecimalField(blank=True, db_column='Desde', decimal_places=1, max_digits=5, null=True)),
                ('hasta', models.DecimalField(blank=True, db_column='Hasta', decimal_places=1, max_digits=5, null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'EscalaProbabilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escnariosriesgos',
            fields=[
                ('codescenarioriesgo', models.AutoField(db_column='CodEscenarioRiesgo', primary_key=True, serialize=False)),
                ('descescenario', models.TextField(blank=True, db_column='DescEscenario', null=True)),
            ],
            options={
                'db_table': 'EscnariosRiesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codestado', models.AutoField(db_column='CodEstado', primary_key=True, serialize=False)),
                ('descestado', models.CharField(blank=True, db_column='DescEstado', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosRiesgo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionCumplimientoNormativo', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'EventosRiesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaActividadesRelacionadasRiesgo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionFrecuencia', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'FrecuenciaActividadesRelacionadasRiesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaControl',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionFrecuenciaControl', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'FrecuenciaControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naturalezacontrol',
            fields=[
                ('codnaturaleza', models.AutoField(db_column='CodNaturaleza', primary_key=True, serialize=False)),
                ('descnaturaleza', models.CharField(blank=True, db_column='DescNaturaleza', max_length=150, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'NaturalezaControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObservacionesAuditoria',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionObservacionesAuditoria', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'ObservacionesAuditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('codpuesto', models.AutoField(db_column='CodPuesto', primary_key=True, serialize=False)),
                ('descpuesto', models.CharField(blank=True, db_column='DescPuesto', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Puestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajesCriteriosImpacto',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('criterio', models.CharField(db_column='Criterio', max_length=200)),
                ('puntaje', models.DecimalField(blank=True, db_column='Puntaje', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'PuntajesCriteriosImpacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajesCriteriosProbabilidad',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('criterio', models.CharField(db_column='Criterio', max_length=200)),
                ('puntaje', models.DecimalField(blank=True, db_column='Puntaje', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'PuntajesCriteriosProbabilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoInstitucional',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionRiesgoInstitucional', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'RiesgoInstitucional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoReputacional',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionRiesgoRepudial', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'RiesgoReputacional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('codriesgo', models.AutoField(db_column='CodRiesgo', primary_key=True, serialize=False)),
                ('descriesgo', models.CharField(blank=True, db_column='DescRiesgo', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Riesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoactividad',
            fields=[
                ('codtipoactividad', models.AutoField(db_column='CodTipoActividad', primary_key=True, serialize=False)),
                ('desctipoactividad', models.CharField(blank=True, db_column='DescTipoActividad', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoActividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoareas',
            fields=[
                ('codtipoarea', models.AutoField(db_column='CodTipoArea', primary_key=True, serialize=False)),
                ('desctipoarea', models.CharField(blank=True, db_column='DescTipoArea', max_length=75, null=True)),
            ],
            options={
                'db_table': 'TipoAreas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrol',
            fields=[
                ('codtipocontrol', models.AutoField(db_column='CodTipoControl', primary_key=True, serialize=False)),
                ('desctipocontrol', models.CharField(blank=True, db_column='DescTipoControl', max_length=150, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'TipoControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproceso',
            fields=[
                ('codtipoproceso', models.AutoField(db_column='CodTipoProceso', primary_key=True, serialize=False)),
                ('desctipoproceso', models.CharField(blank=True, db_column='DescTipoProceso', max_length=75, null=True)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'TipoProceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporaci',
            fields=[
                ('codraci', models.AutoField(db_column='CodRaci', primary_key=True, serialize=False)),
                ('letra', models.CharField(blank=True, db_column='Letra', max_length=1, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=150, null=True)),
            ],
            options={
                'db_table': 'TipoRACI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposriesgos',
            fields=[
                ('codtiporiesgo', models.AutoField(db_column='CodTipoRiesgo', primary_key=True, serialize=False)),
                ('desctiporiesgo', models.CharField(blank=True, db_column='DescTipoRiesgo', max_length=75, null=True)),
            ],
            options={
                'db_table': 'TiposRiesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionesEstadosFinancieros',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DescripcionTransaccionesEstadosFinancieros', max_length=150)),
                ('porcentaje', models.DecimalField(blank=True, db_column='Porcentaje', decimal_places=1, max_digits=5, null=True)),
                ('ponderacion', models.DecimalField(blank=True, db_column='Ponderacion', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'TransaccionesEstadosFinancieros',
                'managed': False,
            },
        ),
    ]
