# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaControl',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('escala', models.IntegerField(blank=True, db_column='Escala', null=True)),
                ('desde', models.DecimalField(blank=True, db_column='Desde', decimal_places=1, max_digits=5, null=True)),
                ('hasta', models.DecimalField(blank=True, db_column='Hasta', decimal_places=1, max_digits=5, null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'EscalaControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntajescriterioscontrol',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('criterio', models.CharField(db_column='Criterio', max_length=200)),
                ('puntaje', models.DecimalField(blank=True, db_column='Puntaje', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'PuntajesCriteriosControl',
                'managed': False,
            },
        ),
    ]
