# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escnariosriesgos',
            fields=[
                ('codescenarioriesgo', models.AutoField(db_column='CodEscenarioRiesgo', primary_key=True, serialize=False)),
                ('descescenario', models.CharField(blank=True, db_column='DescEscenario', max_length=75, null=True)),
            ],
            options={
                'db_table': 'EscnariosRiesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('codriesgo', models.AutoField(db_column='CodRiesgo', primary_key=True, serialize=False)),
                ('descriesgo', models.CharField(blank=True, db_column='DescRiesgo', max_length=75, null=True)),
            ],
            options={
                'db_table': 'Riesgos',
                'managed': False,
            },
        ),
    ]
