# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_escalacontrol_puntajescriterioscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonariesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.IntegerField(blank=True, db_column='Escala', null=True)),
                ('desde', models.DecimalField(blank=True, db_column='Desde', decimal_places=1, max_digits=5, null=True)),
                ('hasta', models.DecimalField(blank=True, db_column='Hasta', decimal_places=1, max_digits=5, null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ZonaRiesgo',
                'managed': False,
            },
        ),
    ]
