# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_escnariosriesgos_riesgos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('codempleado', models.AutoField(db_column='CodEmpleado', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='NombreCompleto', max_length=75, null=True)),
                ('usuarioad', models.CharField(blank=True, db_column='UsuarioAD', max_length=75, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=75, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=75, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=75, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleadoxareas',
            fields=[
                ('codempeladoxarea', models.AutoField(db_column='CodEmpeladoXArea', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='FechaInicio', null=True)),
                ('fecha_final', models.DateTimeField(blank=True, db_column='FechaFinal', null=True)),
                ('habilitado', models.NullBooleanField(db_column='Habilitado')),
            ],
            options={
                'db_table': 'EmpleadoXAreas',
                'managed': False,
            },
        ),
    ]
