from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^administracion/menu/$', views.menu_administracion, name= 'menu_administracion'),
	url(r'^administracion/tipo_area_ingreso/$', views.tipo_area, name= 'tipo_area'),
	url(r'^administracion/tipo_area_editar/(?P<id>.+)/$', views.tipo_area_editar, name= 'tipo_area_editar'),
	url(r'^administracion/areas_ingreso/$', views.areas, name= 'areas'),
	url(r'^administracion/areas_editar/(?P<id>.+)/$', views.areas_editar, name= 'areas_editar'),
	url(r'^administracion/puestos_ingreso/$', views.puestos, name= 'puestos'),
	url(r'^administracion/puestos_editar/(?P<id>.+)/$', views.puestos_editar, name= 'puestos_editar'),
	url(r'^administracion/tipo_proceso_ingreso/$', views.tipoproceso, name = 'tipoproceso'),
	url(r'^administracion/tipo_proceso_editar/(?P<id>.+)/$', views.tipoproceso_editar, name = 'tipoproceso_editar'),
	url(r'^administracion/tipo_actividad_ingreso/$', views.tipoactividad, name = 'tipoactividad'),
	url(r'^administracion/tipo_actividad_editar/(?P<id>.+)/$', views.tipoactividad_editar, name = 'tipoactividad_editar'),
	url(r'^administracion/tipo_control_ingreso/$', views.tipocontrol, name = 'tipocontrol'),
	url(r'^administracion/tipo_control_editar/(?P<id>.+)/$', views.tipocontrol_editar, name = 'tipocontrol_editar'),
	url(r'^administracion/tipo_raci_ingreso/$', views.tiporaci, name = 'tiporaci'),
	url(r'^administracion/tipo_raci_editar/(?P<id>.+)/$', views.tiporaci_editar, name = 'tiporaci_editar'),
	url(r'^administracion/tipo_riesgos_ingreso/$', views.tiporiesgos, name = 'tiporiesgos'),
	url(r'^administracion/tipo_riesgos_editar/(?P<id>.+)/$', views.tiporiesgos_editar, name = 'tiporiesgos_editar'),
	url(r'^administracion/riesgos_ingreso/$', views.categoriariesgos, name = 'categoriariesgos'),
	url(r'^administracion/riesgos_editar/(?P<id>.+)/$', views.categoriariesgos_editar, name = 'categoriariesgos_editar'),
	url(r'^administracion/naturaleza_control_ingreso/$', views.naturalezacontrol, name = 'naturalezacontrol'),
	url(r'^administracion/naturaleza_control_editar/(?P<id>.+)/$', views.naturalezacontrol_editar, name = 'naturalezacontrol_editar'),
	url(r'^administracion/escenario_riesgos_ingreso/$', views.escenarioriesgos, name = 'escenarioriesgos'),
	url(r'^administracion/escenario_riesgos_editar/(?P<id>.+)/$', views.escenarioriesgos_editar, name = 'escenarioriesgos_editar'),
	url(r'^administracion/riesgoinstitucional_ingreso/$', views.riesgoinstitucional, name= 'riesgoinstitucional'),
	url(r'^administracion/riesgoinstitucional_editar/(?P<id>.+)/$', views.riesgoinstitucional_editar, name= 'riesgoinstitucional_editar'),
	url(r'^administracion/riesgoreputacional_ingreso/$', views.riesgoreputacional, name= 'riesgoreputacional'),
	url(r'^administracion/riesgoreputacional_editar/(?P<id>.+)/$', views.riesgoreputacional_editar, name= 'riesgoreputacional_editar'),
	url(r'^administracion/frecuenciaactividades_ingreso/$', views.frecuenciaactividades, name= 'frecuenciaactividades'),
	url(r'^administracion/frecuenciaactividades_editar/(?P<id>.+)/$', views.frecuenciaactividades_editar, name= 'frecuenciaactividades_editar'),
	url(r'^administracion/frecuenciacontroles_ingreso/$', views.frecuenciacontroles, name= 'frecuenciacontroles'),
	url(r'^administracion/frecuenciacontroles_editar/(?P<id>.+)/$', views.frecuenciacontroles_editar, name= 'frecuenciacontroles_editar'),
	url(r'^administracion/areasinvolucradas_ingreso/$', views.areasinvolucradas, name= 'areasinvolucradas'),
	url(r'^administracion/areasinvolucradas_editar/(?P<id>.+)/$', views.areasinvolucradas_editar, name= 'areasinvolucradas_editar'),
	url(r'^administracion/observacionesauditoria_ingreso/$', views.observacionesauditoria, name= 'observacionesauditoria'),
	url(r'^administracion/observacionesauditoria_editar/(?P<id>.+)/$', views.observacionesauditoria_editar, name= 'observacionesauditoria_editar'),
	url(r'^administracion/definicionproceso_ingreso/$', views.definicionproceso, name= 'definicionproceso'),
	url(r'^administracion/definicionproceso_editar/(?P<id>.+)/$', views.definicionproceso_editar, name= 'definicionproceso_editar'),
	url(r'^administracion/cumplimientonormativo_ingreso/$', views.cumplimientonormativo, name= 'cumplimientonormativo'),
	url(r'^administracion/cumplimientonormativo_editar/(?P<id>.+)/$', views.cumplimientonormativo_editar, name= 'cumplimientonormativo_editar'),
	url(r'^administracion/eventosriesgo_ingreso/$', views.eventosriesgo, name= 'eventosriesgo'),
	url(r'^administracion/eventosriesgo_editar/(?P<id>.+)/$', views.eventosriesgo_editar, name= 'eventosriesgo_editar'),
	url(r'^administracion/transaccionesestadosfinancieros_ingreso/$', views.transaccionesestadosfinancieros, name= 'transaccionesestadosfinancieros'),
	url(r'^administracion/transaccionesestadosfinancieros_editar/(?P<id>.+)/$', views.transaccionesestadosfinancieros_editar, name= 'transaccionesestadosfinancieros_editar'),
	url(r'^administracion/unidad_medida_ingreso/$', views.unidad_medida, name= 'unidad_medida'),
	url(r'^administracion/unidad_medida_editar/(?P<id>.+)/$', views.unidad_medida_editar, name= 'unidad_medida_editar'),
	url(r'^administracion/criterios_control_ingreso/$', views.criterios_control, name= 'criterios_control'),
	url(r'^administracion/criterios_control_editar/(?P<id>.+)/$', views.criterios_control_editar, name= 'criterios_control_editar'),
	url(r'^administracion/criterios_impacto_ingreso/$', views.criterios_impacto, name= 'criterios_impacto'),
	url(r'^administracion/criterios_impacto_editar/(?P<id>.+)/$', views.criterios_impacto_editar, name= 'criterios_impacto_editar'),
	url(r'^administracion/criterios_probabilidad_ingreso/$', views.criterios_probabilidad, name= 'criterios_probabilidad'),
	url(r'^administracion/criterios_probabilidad_editar/(?P<id>.+)/$', views.criterios_probabilidad_editar, name= 'criterios_probabilidad_editar'),
	url(r'^administracion/escala_control_ingreso/$', views.escala_control, name= 'escala_control'),
	url(r'^administracion/escala_control_editar/(?P<id>.+)/$', views.escala_control_editar, name= 'escala_control_editar'),
	url(r'^administracion/escala_control_especial/$', views.escala_control_especial, name= 'escala_control_especial'),
	url(r'^administracion/escala_control_especial_editar/(?P<id>.+)/$', views.escala_control_especial_editar, name= 'escala_control_especial_editar'),
	url(r'^administracion/escala_impacto_ingreso/$', views.escala_impacto, name= 'escala_impacto'),
	url(r'^administracion/escala_impacto_editar/(?P<id>.+)/$', views.escala_impacto_editar, name= 'escala_impacto_editar'),
	url(r'^administracion/escala_impacto_especial/$', views.escala_impacto_especial, name= 'escala_impacto_especial'),
	url(r'^administracion/escala_impacto_especial_editar/(?P<id>.+)/$', views.escala_impacto_especial_editar, name= 'escala_impacto_especial_editar'),
	url(r'^administracion/escala_probabilidad_ingreso/$', views.escala_probabilidad, name= 'escala_probabilidad'),
	url(r'^administracion/escala_probabilidad_editar/(?P<id>.+)/$', views.escala_probabilidad_editar, name= 'escala_probabilidad_editar'),
	url(r'^administracion/escala_probabilidad_especial/$', views.escala_probabilidad_especial, name= 'escala_probabilidad_especial'),
	url(r'^administracion/escala_probabilidad_especial_editar/(?P<id>.+)/$', views.escala_probabilidad_especial_editar, name= 'escala_probabilidad_especial_editar'),
	url(r'^administracion/zona_riesgo_ingreso/$', views.zonas_ingreso, name= 'zonas_ingreso'),
	url(r'^administracion/zona_riesgo_editar/(?P<id>.+)/$', views.zonas_editar, name= 'zonas_editar'),
	url(r'^administracion/zona_riesgo_especial/$', views.zonas_especiales, name= 'zonas_especiales'),
	url(r'^administracion/zona_riesgo_especial_editar/(?P<id>.+)/$', views.zonas_especiales_editar, name= 'zonas_especiales_editar'),

	url(r'^ajax/$', views.ajax, name='ajax'),

]
